version: '3'

services:

  node-red:
    image: nodered/node-red
    ports:
      - '1880:1880'
    volumes:
      - ./node-red/data:/data
    restart: always

  deconz:
    image: marthoc/deconz:stable
    network_mode: host
    restart: always
    volumes:
      - ./deconz/data:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyAMA0
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
